### ISSUE TITLE
issue installing on win 10, vs2015, EDsdk 3.4

### ISSUE THREAD

**Issue by rwebber** [elliotwoods/ofxCanon#2]
Unable to open the example files.
#include "EDSDK.h" not found.
Looking at the setup for ofxCanonLib in the exampleSimple, I see that for debug, the additional include directories include ..\..\..\addons\ofxCanon\libs\EDSDK\include
My SDK folder has "Dll","Header", and "Library". No include.

Looking at the "contents-visual_studio.txt" I gathered that I needed to add the EDSDK to the same folder (into libs). My EDSDK doesn't have the Bin or Lib folders either.. no source files. Again only "Dll","Header", and "Library".

Is there a source version of the EDSDK that I need to locate?

**Comment by elliotwoods** [comment]
inside the zip you want to get:
`0304\Windows\EDSDK\Header` (this is your includes)
`0304\Windows\EDSDK_64\Dll` (this is the bins)
`0304\Windows\EDSDK_64\Library` (this is the libs)

**Comment by elliotwoods** [comment]
so i presume its just that the naming convention between oF and EDSDK is a little different. let me know if this works out for you. if not we can reopen the issue

**Comment by rwebber** [comment]
OK, have got example.sln to build for debug x64. (connects and runs with my camera :)

I copied the folders to "OFPATH\addons\ofxCanon\libs\EDSDK" and renamed them according to your previous message. Thanks.

I had to change a couple paths in the ofxCanonLib properties for debug |x64.  (only one I have setup so far)
added additional linker directories: "..\..\..\addons\ofxCanon\libs\EDSDK\includes"
and change any path like this:
"..\..\..\addons\ofxCanon\libs\EDSDK\lib\vs\$(Platform)"
to: "..\..\..\addons\ofxCanon\libs\EDSDK\lib\"

It seems the sdk no longer has the VS & platform folders.

Is there a preferred way to make these types of changes?
Also, is it required to manually copy the EDSDK.dll to the bin folder? (thats what I did)

I get some messages about features being limited or unsupported in 64bit, so I think I will switch to the 32bit sdk files. Based on the SDK as I received it, it would seem to make sense to me to use "libs\EDSDK" for the x86 linking, and "libs\EDSDK_64" for the x64 since this is how the SDK has this broken down now.

Again, thank-you for both the great work, and the support.

**Comment by elliotwoods** [comment]
It sounds (again) like you're trying to follow the origin (EDSDK) naming convention too strongly and not following the destination (oF) folder naming convention 

I'll keep this issue open until there's a good way of explaining the translation. Perhaps you could help?

Simply the naming convention between of and edsdk is different and the inner folder config is different also

I'm dubious about making a script to copy the files into exact position because that would be specific per OS and EDSDK version. But maybe you could recommend the beatnik light touch to make which would guide users in the right direction?
